services:
  db:
    image: postgres:16-alpine
    container_name: suis-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Enza!2003
      POSTGRES_DB: suis_db
    ports:
      - "5432:5432"
    volumes:
      - suis_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d suis_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suis-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      COOKIE_SECURE: "false"
      DATABASE_URL: postgresql://postgres:Enza%212003@db:5432/suis_db?schema=public
    ports:
      - "3000:3000"

volumes:
  suis_postgres_data:
